language: php

php:
    - "5.5"

env:
    - DB=mysql

before_script:
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -uroot -e 'DROP DATABASE IF EXISTS risoluto_db_test;'; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS risoluto_db_test;'; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -uroot -e 'DROP TABLE IF EXISTS risoluto_db_test.risoluto_db_test'; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -uroot -e 'CREATE TABLE IF NOT EXISTS risoluto_db_test.risoluto_db_test(id int(11) unsigned NOT NULL AUTO_INCREMENT, column1 varchar(100) DEFAULT NULL, column2 varchar(100) DEFAULT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;'; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -uroot -e 'INSERT INTO risoluto_db_test.risoluto_db_test(id, column1, column2) VALUES (1, "id1:column1", "id1:column2");'; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -uroot -e 'INSERT INTO risoluto_db_test.risoluto_db_test(id, column1, column2) VALUES (2, NULL, NULL);'; fi"
    - cd ./risoluto/lib/
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --no-interaction --dev
    - chmod -R 777 ../../risoluto/data/

script:
    - sh ./phpunit_run.sh

notifications:
  email:
    recipients:
      - dev@risoluto.org