language: php

php:
    - "5.5"

env:
    - DB=mysql

before_script:
    - cd ./risoluto/lib/
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --no-interaction --dev
    - chmod -R 777 ../../risoluto/data/

script:
    - sh ./phpunit_run.sh

notifications:
  email:
    recipients:
      - dev@risoluto.org
    on_success: always
    on_failure: always