language: php

php:
    - "5.5"

env:
    - DB=mysql

before_script:
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -uroot -e 'DROP DATABASE IF EXISTS risoluto_db_test;'; fi"
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS risoluto_db_test;'; fi"
    - cd ./risoluto/lib/
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --no-interaction --dev
    - chmod -R 777 ../../risoluto/data/

script:
    - sh ./phpunit_run.sh

notifications:
  email:
    recipients:
      - dev@risoluto.org